# src/main/resources/application-test.properties

# Perfil para tests

# ===== Spring =====
spring.datasource.url=jdbc:postgresql://localhost:5432/sip_project
spring.datasource.username=dev_user
spring.datasource.password=dev_password

# ==== JPA ====
# hibernate solo se encarga de validar, no genera nada.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# ===== Flyway =====
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.clean-disabled=false

# ==== Seed Admin ====
app.seed-admin=true