# Archivo de config. para correr localmente sin tocar tecnologias en la nube.

spring.datasource.url=jdbc:postgresql://localhost:5432/sip_project
spring.datasource.username=dev_user
spring.datasource.password=dev_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081