# src/main/resorces/application-local.properties

# Perfil para ejecutar todo en modo local

# ===== Spring =====
spring.datasource.url=jdbc:postgresql://localhost:5432/sip_project
spring.datasource.username=dev_user
spring.datasource.password=dev_password

# ===== Server =====
server.port=8081